# Generated by Django 2.1.3 on 2019-08-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmark_set',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='post.Post'),
        ),
    ]
